In [5]:
import numpy as np
arr = np.zeros(10)
print(arr)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [6]:
arr4 = np.ones(10)
print(arr4)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [7]:
arr4 = np.ones(10)*5
print(arr4)


[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [8]:
arr4 = np.ones(10)*10
print(arr4)

[10. 10. 10. 10. 10. 10. 10. 10. 10. 10.]


In [9]:
arr4 = np.ones(10)*20
print(arr4)

[20. 20. 20. 20. 20. 20. 20. 20. 20. 20.]


In [10]:
arr4 = np.ones(10)*50
print(arr4)

[50. 50. 50. 50. 50. 50. 50. 50. 50. 50.]
